sudo: required
dist: trusty
addons:
  chrome: stable
  apt:
    packages:
    - dpkg
language: node_js
node_js:
- 10

branches:
  # blacklist
  except:
  - main
  - development
  # whitelist
  only:
  - master

env:
  global:
  - secure: ZE1HxzNziNKTU57cAcul05JwGDXnTsOyxeYV5isicQRwfC8z5visSi664eSTAMJNN1eQDCMtIb2Pnet5tEw9r/RHNI4CtgWTNTWTwC+wOWj4e6PM8epVbzK/DEOIIpskHDSLKZ0GvK0jRIGuYWFZciQdVWJPcH4urzMi0fjGQXwUx69XCQd1D7ulcz00Ay1nc+RZIZ/4P8igtjATD7IQOrxDiJEEPmppCyLJx9JFmuu855Zua0uqnOyY6qnP7LipWOHPzKh7JcRfp6KPs2XwTD568WKzbPeE4aIlqSA3RoHpBb0FTZuwfckpI8DUVF/Ntl8oDdTl0dad8YzvoYCqqL84nIo6RrTkanTAnimo8ecZMKRJH8zrLhPsOqycGab3EVMRZ0Gs82u8fNhoHztPr0WqdLqAoVSEBP2Hw7Wme8LzFQnWHOc1EBYR9VF2FK+RumnaKaLvYuO/qOMmSnTDJrLZxiDyn2DfEoUHKCGu952jyCJUoR9ikxxbhwq2P3TvRduhGV3Pklw4+oVE4MiN7lQtpf4fUAkch33H+KG9YJdKwqrhA2KatytKxHtL2iu9JomurHbbtB3LLHmw64+HUhmK4goTEjrLea32E2RT8g+Ziz9axSZTpesxQOMVzF8Bo8Hfwq3JhH2u7fbaIyjsUcJu95wl5vi0n6A323Nqeug=
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
cache:
  directories:
  - "./node_modules"
install:
- npm install
- npm install -g angular-cli-ghpages
script:
- npm run build-lib
- npm run build-ghpages
after_success:
- if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ] ; then
  angular-cli-ghpages --dir="dist-ghpages" --no-silent --repo="https://${GH_TOKEN}@github.com/tuyenttran/ngx-fontawesome.git"
  --name="tuyenttran" --email="anhtuyen.tran@gmail.com"; fi
before_deploy:
- cd dist/@ui4ngx/fontawesome/
deploy:
  provider: npm
  email: anhtuyen.tran@gmail.com
  api_key:
    secure: MAcCmaeET9LhvNKjk7xU/6Kco20ye65sAU5aM8A5/qD0oVDqJ0JAGQw78lsu3VcS/7Na/J7KBMxIcljFNSoCRIeGLKoupnScLwibOCIMS/t85MaCKHzE/NIS9vvfzCarprysplz7oNYtwSPVnGxecmdoEYb2C0EMLxsITyjT4P/e5BkZOyAg7pxlRc7riAZ/HK35NF68RxD703+5UrnwvVLt+cJqwYTr2DPIhwp88ysBXGuVj9ipxNKkY9uHka2tvrwLCok9nc7lAWQf8sNGTEKX3z+YFXSXgnE1GN5PkWftJr0bk/omjPdSL9Dlg6i1xz/1ofjof4KxNaddN7onvfCJvdSGiqSY0vbz+muTXuPz9fCswfodcVTWzzNs/rwWzJw/wGKPkEns+8ANkvCXEhsMyIYUgn5QPNEhVtrlz7JnkTFWU/ov7bxNDNz6qsLvCpR1g42JMi7mixL8G3uoSkWCxLc+ffSEDsz4g8JzvMsb3PCcIAclyubTP/Ef1SkHuqqIdVIVbTeD8r4ig8S+1zj/IxPG5n+Yrbw5UQICK1XDSPM843DhtMQOi4cdLiwMBAKqfqmal2FtEAeoI28lomBfUdg/A6hCE9Of3GMfaZx7Jkl0p6JQkb4E+VKL52j/DsROlbXtIqkGWc2d6Rn4wyIIfLjnlHvhlh5NyPxLwV0=
  on:
    branch: master
    tags: true
  skip_cleanup: true
