export * from './utils/random-utils';
export * from './component/symbol/symbol.interface';
export * from './component/icons/fontawesome.interface';
export * from './service/symbol.service';
export * from './component/symbol/symbol.component';
export * from './component/icons/fontawesome.component';
export * from './component/icons/fontawesome-svg.component';
export * from './component/text/layers-text.directive';
export * from './ngx-fontawesome.module';
